# Generated by Django 4.2.11 on 2024-05-17 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_remove_useraddress_refered_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('alt_mobile', models.CharField(blank=True, max_length=10)),
                ('address', models.TextField()),
                ('town', models.CharField(max_length=150)),
                ('zipcode', models.IntegerField()),
                ('nearby_location', models.CharField(blank=True, max_length=255)),
                ('district', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('created', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
